name: Lint, Test the Plugin Build

# 
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  milestone:
    types: [ "closed" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: install web-ext
      run: |
        sudo apt-get update
        sudo apt-get install -y web-ext

    - name: lint
      run: |
        web-ext lint

    - name: build
      run: |
        web-ext build
